"""

Revision ID: 1d700b1a6d54
Revises: 7ca2d80b7580
Create Date: 2024-06-11 14:09:40.330967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d700b1a6d54'
down_revision = '7ca2d80b7580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_url_category_id_category'), 'url', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_url_category_id_category'), 'url', type_='foreignkey')
    op.drop_column('url', 'category_id')
    # ### end Alembic commands ###
