"""

Revision ID: 3fdcee8882b7
Revises: 4c94ba8d0609
Create Date: 2024-06-21 14:52:04.934075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdcee8882b7'
down_revision = '4c94ba8d0609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image_url')
    # ### end Alembic commands ###
