"""

Revision ID: 55eda3c444b6
Revises: ed56f6060e04
Create Date: 2024-06-11 11:56:37.264538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55eda3c444b6'
down_revision = 'ed56f6060e04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'language')
    op.add_column('url', sa.Column('language', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'language')
    op.add_column('source', sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
