"""

Revision ID: 7bb6e9ede72e
Revises: 3a0fdba3217f
Create Date: 2024-06-07 11:16:17.957209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb6e9ede72e'
down_revision = '3a0fdba3217f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
