"""

Revision ID: eecb2cfb7e27
Revises: 024a2a85fbb7
Create Date: 2024-06-25 14:49:13.645348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecb2cfb7e27'
down_revision = '024a2a85fbb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similars',
    sa.Column('title1', sa.Text(), nullable=True),
    sa.Column('title2', sa.Text(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similars')),
    sa.UniqueConstraint('similarity', name=op.f('uq_similars_similarity')),
    sa.UniqueConstraint('title1', name=op.f('uq_similars_title1')),
    sa.UniqueConstraint('title2', name=op.f('uq_similars_title2'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similars')
    # ### end Alembic commands ###
