"""

Revision ID: faede99f9a28
Revises: d91ebcea7e06
Create Date: 2024-06-25 16:13:57.541348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faede99f9a28'
down_revision = 'd91ebcea7e06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similars')
    op.drop_column('news', 'similarity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('similarity', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('similars',
    sa.Column('title1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('similarity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_similars')
    )
    # ### end Alembic commands ###
